List<Map<String, dynamic>> schema = [
  {"alias": "_id", "title": "ID", "type": "string", "visible": 0, "hide": 1},
  {"alias": "string_1", "title": "String 1", "type": "string", "visible": 1, "hide": 0},
  {"alias": "string_2", "title": "String 2", "type": "string", "visible": 1, "hide": 0},
  {"alias": "string_3", "title": "String 3", "type": "string", "visible": 1, "hide": 0},
  {"alias": "number_1", "title": "Number 1", "type": "number", "visible": 1, "hide": 0},
  {"alias": "number_2", "title": "Number 2", "type": "number", "visible": 1, "hide": 0},
  {"alias": "number_3", "title": "Number 3", "type": "number", "visible": 1, "hide": 0},
  {"alias": "datetime_1", "title": "Datetime 1", "type": "date-time", "visible": 1, "hide": 0},
  {"alias": "datetime_2", "title": "Datetime 2", "type": "date-time", "visible": 1, "hide": 0},
  {"alias": "datetime_3", "title": "Datetime 3", "type": "date-time", "visible": 1, "hide": 0},
  {"alias": "created_at", "title": "Created At", "type": "date-time", "visible": 0, "hide": 1},
  {"alias": "updated_at", "title": "Updated At", "type": "date-time", "visible": 0, "hide": 1},
  {"alias": "deleted_at", "title": "Deleted At", "type": "date-time", "visible": 0, "hide": 1},
];
